version: '3.9'

services:
  go-app:
    container_name: go-products
    build:
      context: .
      dockerfile: Dockerfile
    image: ibra/go-products:1.0.0
    environment:
      DATABASE_URL: "host=go_db user=postgres password=postgres dbname=postgres sslmode=disable"
    ports:
      - "8003:8003"  # Updated port to 8003
    depends_on:
      - go_db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/healthz"]
      interval: 10s
      timeout: 5s
      retries: 3

  go_db:
    container_name: go_db_products
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5436:5432"  # Changed to avoid conflicts
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-h", "127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  pgdata: {}

networks:
  default:
    external:
      name: shared_network
